# Generated by Django 5.1.1 on 2024-10-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trip", "0003_rename_place_trip_locality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nazwa wydarzenia", max_length=255),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Data rozpoczęcia wydarzenia"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="Data zakończenia wydarzenia"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Załącznik wydarzenia",
                        null=True,
                        upload_to="event_attachments/",
                    ),
                ),
                (
                    "links",
                    models.URLField(
                        blank=True, help_text="Powiązane linki URL", null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Cena wydarzenia", max_digits=10
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notatki dotyczące wydarzenia", null=True
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("accommodation", "Zakwaterowanie"),
                            ("vehicle_rental", "Wypożyczenie pojazdu"),
                            ("activities", "Aktywności"),
                            ("other", "Inne"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=50)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
            ],
        ),
    ]
