# Generated by Django 5.1.1 on 2024-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="service_picture",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
