# Generated by Django 5.1.1 on 2024-10-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_servicetype_service_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetype",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="event.event"
            ),
        ),
    ]
