# Generated by Django 5.1.1 on 2024-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_servicetype_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TRANSPORT", "Transport"),
                            ("ACCOMMODATION", "Zakwaterowanie"),
                            ("VEHICLE_RENTAL", "Wypożyczenie pojazdu"),
                            ("ACTIVITIES", "Aktywności"),
                            ("OTHER", "Inne"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_sub_type", models.CharField(max_length=50)),
                ("img_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="event_sub_type",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name="ServiceType",
        ),
    ]
