# Generated by Django 5.1.1 on 2024-10-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_event_event_sub_type_alter_event_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("accommodation", "Zakwaterowanie"),
                            ("vehicle_rental", "Wypożyczenie pojazdu"),
                            ("activities", "Aktywności"),
                            ("other", "Inne"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_label", models.CharField(max_length=50)),
                ("img_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="eventsubtype",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("transport", "Transport"),
                    ("accommodation", "Zakwaterowanie"),
                    ("vehicle_rental", "Wypożyczenie pojazdu"),
                    ("activities", "Aktywności"),
                    ("other", "Inne"),
                ],
                max_length=50,
            ),
        ),
    ]
