# Generated by Django 5.1.1 on 2024-11-03 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_eventlabel_alter_eventsubtype_event_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventSubType",
            new_name="EventSubLabel",
        ),
        migrations.RemoveField(
            model_name="event",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="event",
            name="links",
        ),
        migrations.RemoveField(
            model_name="eventlabel",
            name="event_label",
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="EventAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="Link associated with the event")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="event.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="Link associated with the event")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="event.event",
                    ),
                ),
            ],
        ),
    ]
