# Generated by Django 5.1.1 on 2024-11-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_rename_eventsubtype_eventsublabel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventlink",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="attachments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of attachments associated with the event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="links",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of links associated with the event",
            ),
        ),
        migrations.DeleteModel(
            name="EventAttachment",
        ),
        migrations.DeleteModel(
            name="EventLink",
        ),
    ]
