# Generated by Django 5.1.1 on 2024-10-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="travel_end_at",
            new_name="end_at",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="travel_place",
            new_name="place",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="travel_start_at",
            new_name="start_at",
        ),
    ]
