# Generated by Django 5.1.1 on 2024-10-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_rename_travel_end_at_trip_end_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="place",
            new_name="locality",
        ),
    ]
