# Generated by Django 5.1.1 on 2024-10-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0003_rename_place_trip_locality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="locality",
            new_name="desitnation",
        ),
    ]
