# Generated by Django 5.1.1 on 2024-10-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0004_rename_locality_trip_desitnation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="desitnation",
            new_name="destination",
        ),
    ]
